"""Durable memory table initialization for SQLite and PostgreSQL."""

from __future__ import annotations


MEMORY_TABLE_NAME = "memory"


class MemorySchemaError(
    RuntimeError
):
    """Raised without leaking database credentials."""

    def __init__(self):
        super().__init__(
            "Memory schema initialization failed."
        )


def _close_safely(
    resource,
) -> None:
    close = getattr(
        resource,
        "close",
        None,
    )

    if callable(close):
        close()


def initialize_memory_schema(
    connection,
    *,
    is_postgresql: bool,
) -> None:
    cursor = connection.cursor()

    try:
        if is_postgresql:
            cursor.execute(
                f"""
                CREATE TABLE IF NOT EXISTS
                public.{MEMORY_TABLE_NAME} (
                    id BIGINT
                        GENERATED BY DEFAULT
                        AS IDENTITY
                        PRIMARY KEY,
                    role TEXT NOT NULL,
                    content TEXT NOT NULL,
                    legacy_source_id BIGINT UNIQUE,
                    created_at TIMESTAMPTZ
                        NOT NULL
                        DEFAULT CURRENT_TIMESTAMP
                )
                """
            )

            cursor.execute(
                f"""
                CREATE INDEX IF NOT EXISTS
                ix_memory_id_desc
                ON public.{MEMORY_TABLE_NAME}
                (id DESC)
                """
            )

        else:
            cursor.execute(
                f"""
                CREATE TABLE IF NOT EXISTS
                {MEMORY_TABLE_NAME} (
                    id INTEGER
                        PRIMARY KEY
                        AUTOINCREMENT,
                    role TEXT,
                    content TEXT
                )
                """
            )

        connection.commit()

    except Exception as error:
        try:
            connection.rollback()
        except Exception:
            pass

        raise MemorySchemaError() from error

    finally:
        _close_safely(
            cursor
        )
